mod generic_largest_test;
mod generic_struct_test;
mod scope_borrowing_test;
mod scope_operator_test;
mod types_tuple_test;
mod pointer_ref_and_deref_test;
mod scope_lifetime_test;
mod crate_test_veho_dependency;
mod struct_callable;