pub use amber::AMBER;
pub use blue::BLUE;
pub use blue_grey::BLUE_GREY;
pub use brown::BROWN;
pub use cyan::CYAN;
pub use deep_orange::DEEP_ORANGE;
pub use deep_purple::DEEP_PURPLE;
pub use green::GREEN;
pub use grey::GREY;
pub use indigo::INDIGO;
pub use light_blue::LIGHT_BLUE;
pub use light_green::LIGHT_GREEN;
pub use lime::LIME;
pub use orange::ORANGE;
pub use pink::PINK;
pub use purple::PURPLE;
pub use red::RED;
pub use teal::TEAL;
pub use yellow::YELLOW;

mod amber;
mod blue;
mod blue_grey;
mod brown;
mod cyan;
mod deep_orange;
mod deep_purple;
mod green;
mod grey;
mod indigo;
mod light_blue;
mod light_green;
mod lime;
mod orange;
mod pink;
mod purple;
mod red;
mod teal;
mod yellow;

